# Generated by Django 3.2.6 on 2023-03-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
