# Generated by Django 3.2.6 on 2023-03-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numeroID',
            field=models.IntegerField(),
        ),
    ]
